- name: Install etcd package
  package:
    name: etcd-server
    state: present

- name: Set member name
  lineinfile:
    dest: "/etc/default/etcd"
    line: "ETCD_NAME=\"{{ ansible_hostname }}\""
    regexp: ".*ETCD_NAME.*"

- name: Set data directory
  lineinfile:
    dest: "/etc/default/etcd"
    line: "ETCD_DATA_DIR=\"/var/lib/etcd/patroni\""
    regexp: ".*ETCD_DATA_DIR.*"

- name: Listen for other cluster peers
  lineinfile:
    dest: "/etc/default/etcd"
    line: "ETCD_LISTEN_PEER_URLS=\"http://{{ hostvars[ansible_hostname]['patroni_main_ip'] }}:{{ etcd_peer_port }}\""
    regexp: ".*ETCD_LISTEN_PEER_URLS.*"

- name: Setup advertised peer communication URL
  lineinfile:
    dest: "/etc/default/etcd"
    line: "ETCD_INITIAL_ADVERTISE_PEER_URLS=\"http://{{ hostvars[ansible_hostname]['patroni_main_ip'] }}:{{ etcd_peer_port }}\""
    regexp: ".*ETCD_INITIAL_ADVERTISE_PEER_URLS.*"

- name: Enable client listen interface
  lineinfile:
    dest: "/etc/default/etcd"
    line: "ETCD_LISTEN_CLIENT_URLS=\"http://localhost:{{ etcd_client_port }},http://{{ hostvars[ansible_hostname]['patroni_main_ip'] }}:{{ etcd_client_port }}\""
    regexp: ".*ETCD_LISTEN_CLIENT_URLS.*"

- name: Advertise client interface
  lineinfile:
    dest: "/etc/default/etcd"
    line: "ETCD_ADVERTISE_CLIENT_URLS=\"{% for ip in patroni_ips %}http://{{ ip }}:{{ etcd_client_port }}{% if not loop.last %},{% endif %}{% endfor %}\""
    regexp: ".*ETCD_ADVERTISE_CLIENT_URLS.*"

- name: Setup URLs of initials members
  lineinfile:
    dest: "/etc/default/etcd"
    line: "ETCD_INITIAL_CLUSTER=\"{% for host in patroni_hosts %}{{ host }}=http://{{ hostvars[host]['patroni_main_ip'] }}:{{ etcd_peer_port }}{% if not loop.last %},{% endif %}{% endfor %}\""
    regexp: ".*ETCD_INITIAL_CLUSTER.*"

- name: Enable V2 API
  lineinfile:
    dest: "/etc/default/etcd"
    line: "ETCD_ENABLE_V2=\"true\""
    regexp: ".*ETCD_ENABLE_V2.*"
  when: dcs == "etcd"

- name: systemctl daemon-reload / start etcd
  systemd:
    daemon_reload: yes
    name: etcd
    state: restarted
    enabled: yes
