- name: Install postgresql-common
  package:
    name: postgresql-common
    state: present

- name: Disable auto creation of PostgreSQL clusters
  lineinfile:
    dest: "/etc/postgresql-common/createcluster.conf"
    line: "create_main_cluster = false"
    regexp: ".*create_main_cluster.*"

- name: Install PostgreSQL Server
  package:
    name:
      - "postgresql-{{ psql_major_version }}"
      - "postgresql-contrib-{{ psql_major_version }}"
      - "postgresql-client-{{ psql_major_version }}"
    state: present
