- name: Determine and store main IPv4 address
  ansible.builtin.set_fact:
    patroni_main_ip: "{{ main_ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}"

- name: Apply postgresql parameters
  ansible.builtin.shell: patronictl -c /etc/patroni/15-main.yml edit-config --force --pg {{ item.key }}="{{ item.value }}"
  loop: "{{ psql_parameters | dict2items }}"
  when: psql_parameters and inventory_hostname == patroni_hosts[0]
  register: param_diffs

- debug:
    msg: "{{ param_diffs.results | map(attribute='stdout') | join('\n') }}"
  when: psql_parameters and inventory_hostname == patroni_hosts[0]

- name: Copy pga_hba from template
  template:
    src: templates/pg_hba.j2
    dest: /tmp/pg_hba.tmp
  when: inventory_hostname == patroni_hosts[0]

- name: Apply pga_hba
  ansible.builtin.shell: patronictl -c /etc/patroni/15-main.yml edit-config --force --apply /tmp/pg_hba.tmp
  when: inventory_hostname == patroni_hosts[0]
  register: hba_diffs

- debug:
    msg: "{{ hba_diffs.stdout }}"
  when: inventory_hostname == patroni_hosts[0]
